# Generated by Django 3.1.7 on 2021-03-10 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UpdatePromoProduit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('tigId', models.IntegerField(default='-1')),
                ('sale', models.BooleanField(default=False)),
                ('discount', models.FloatField(default='0.0')),
            ],
            options={
                'ordering': ('tigId', 'sale', 'discount'),
            },
        ),
    ]
